# Secret para credenciais do banco de dados do lanchonetews
apiVersion: v1
kind: Secret
metadata:
  name: lanchonetews-db-credentials
  namespace: {{ .Values.global.namespace | default "lanchonetews" | quote }}
  labels:
    app: lanchonetews
type: Opaque
data:
  DB_USER: {{ .Values.global.database.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.global.database.dbPassword | b64enc | quote }}
