# Service para expor o lanchonetews
apiVersion: v1
kind: Service
metadata:
  name: lanchonetews
  namespace: {{ .Values.global.namespace | default "lanchonetews" | quote }}
  labels:
    app: lanchonetews
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.lanchonetews.service.type | default "NodePort" }}
  ports:
    - name: api
      port: {{ .Values.lanchonetews.service.port | default 3000 }}
      targetPort: 3000
      protocol: TCP
      nodePort: {{ .Values.lanchonetews.service.nodePort | default 31136 }}
  selector:
    app: lanchonetews
