# Secret para credenciais do PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: {{ .Values.global.namespace | default "lanchonetews" }}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  POSTGRES_USER: {{ .Values.global.database.dbUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.database.dbPassword | b64enc | quote }}
  POSTGRES_DB: {{ .Values.global.database.DB_DATABASE | default "lanchonete_ws" | b64enc | quote }}
